concrete ExpandedLexiconEn of Words = {
  lincat
    CN = {{s : Str}}; -- Common Noun (Simplified)
  lin
    モ.バ.イ.ル_0 : CN = {s = "Mobile"};
    気.遣.い_1 : CN = {s = "I care."};
    下.が.る_2 : CN = {s = "Stay back."};
    強.め.る_3 : CN = {s = "Strengthen"};
    ノ.ン.ス.ト.ッ.プ_4 : CN = {s = "Non-stop"};
    上.が.る_5 : CN = {s = "Up."};
    オ.ル.タ.ネ.ー.タ.ー_6 : CN = {s = "Altaneter"};
    蓄.電.池_7 : CN = {s = "A battery."};
    ぎ.じ.ゅ.つ_8 : CN = {s = "Oh, my God."};
    心.配.り_9 : CN = {s = "I'm worried."};
    ﾊ.ﾞ.ｯ.ﾃ.ﾘ.ｰ_10 : CN = {s = "A battery."};
    高.め.よ_11 : CN = {s = "I'm going to raise you up."};
    長.距.離_12 : CN = {s = "Long distance"};
    ア.ン.マ_13 : CN = {s = "Umma."};
    高.ま.る_14 : CN = {s = "Increase"};
    充.電_15 : CN = {s = "Charge."};
    関.越.道_16 : CN = {s = "Kanji way."};
    リ.チ.ウ.ム.イ.オ.ン.バ.ッ.テ.リ.ー_17 : CN = {s = "Lithium ion battery."};
    B.a.t.t.e.r.y_18 : CN = {s = "Browsing"};
    強.ま.っ_19 : CN = {s = "It's strong."};
    薄.ま.る_20 : CN = {s = "It's thin."};
    デ.ジ.タ.ル.技.術_21 : CN = {s = "Digital technology."};
    バ.ッ.テ.リ_22 : CN = {s = "battery"};
    最.先.端_23 : CN = {s = "Preliminary"};
    コ.ー.ド.レ.ス_24 : CN = {s = "Codeless."};
    B.a.t.t.e.r.y_25 : CN = {s = "baby"};
    気.遣.っ_26 : CN = {s = "I care."};
    E.n.e.l.o.o.p_27 : CN = {s = "eneloop"};
    ハ.イ.ス.ピ.ー.ド_28 : CN = {s = "High speed"};
    リ.チ.ウ.ム_29 : CN = {s = "Lithium"};
    ソ.ー.ラ.ー_30 : CN = {s = "Solar"};
    L.i.p.o_31 : CN = {s = "Lipo"};
    あ.が.る_32 : CN = {s = "Up."};
    増.え.る_33 : CN = {s = "Increase"};
    M.i.c.r.o.u.s.b_34 : CN = {s = "MicroUSB"};
    オ.ル.タ.ネ.ー.タ_35 : CN = {s = "Altanita"};
    近.距.離_36 : CN = {s = "Nearest"};
    向.上_37 : CN = {s = "Improved"};
    高.速_38 : CN = {s = "Fast"};
    ニ.ッ.カ.ド_39 : CN = {s = "Nickard."};
    高.ま.れ_40 : CN = {s = "Up."};
    目.配.り_41 : CN = {s = "Eyes-to-eye"};
    高.速.度_42 : CN = {s = "High Speed"};
    カ.ー.チ.ャ.ー.ジ.ャ.ー_43 : CN = {s = "Casualties."};
    リ.チ.ウ.ム.イ.オ.ン.バ.ッ.テ.リ_44 : CN = {s = "Lithium ion battery"};
    テ.ク.ノ.ロ.ジ.ー_45 : CN = {s = "Technology"};
    エ.ネ.ル.ー.プ_46 : CN = {s = "Energon"};
    自.動.車_47 : CN = {s = "Cars."};
    ハ.イ.ウ.ェ.イ_48 : CN = {s = "Highway."};
    バ.ッ.テ.リ.ー_49 : CN = {s = "A battery."};
    心.遣.い_50 : CN = {s = "Attention."};
    技.術_51 : CN = {s = "Technologies"};
    高.ま.ら_52 : CN = {s = "It's going to go up."};
    働.き.か.け_53 : CN = {s = "Actions"};
    乾.電.池_54 : CN = {s = "It's a dry battery."};
    ノ.ウ.ハ.ウ_55 : CN = {s = "How do you do that?"};
    バ.ッ.テ.リ.ー.チ.ャ.ー.ジ.ャ.ー_56 : CN = {s = "A battery trucker."};
    強.ま.る_57 : CN = {s = "Increase"};
    高.ま.り_58 : CN = {s = "It's rising."};
    高.め.る_59 : CN = {s = "Increase"};
    開.発_60 : CN = {s = "Development"};
    グ.ル.ー.ヴ_61 : CN = {s = "Grove."};
    気.づ.か.い_62 : CN = {s = "I don't care."};
    気.配.り_63 : CN = {s = "I can't believe it."};
    キ.ャ.パ.シ.タ_64 : CN = {s = "Capacuda"};
    テ.ク.ニ.ッ.ク_65 : CN = {s = "Technique"};
    こ.う.そ.く_66 : CN = {s = "This is a candle."};
    M.a.h_67 : CN = {s = "mAh"};
    コ.ン.セ.ン.ト_68 : CN = {s = "Consult"};
    新.東.名_69 : CN = {s = "Newt's name."};
    M.i.c.r.o.u.s.b_70 : CN = {s = "MicroSB"};
    弱.ま.る_71 : CN = {s = "Fading"};
    ラ.イ.ト.ニ.ン.グ.ケ.ー.ブ.ル_72 : CN = {s = "Lightning cable."};
    電.池_73 : CN = {s = "ELECTRONICS"};
    高.ま.っ_74 : CN = {s = "It's up."};
    気.遣.わ_75 : CN = {s = "I care."};
    強.ま.り_76 : CN = {s = "It's getting stronger."};
    ニ.カ.ド_77 : CN = {s = "Nicad."};
    底.上.げ_78 : CN = {s = "Up and at the bottom."};
    配.慮_79 : CN = {s = "Consideration"};
    リ.チ.ウ.ム.ポ.リ.マ.ー_80 : CN = {s = "Lithium Polymer"};
    電.気_81 : CN = {s = "Electricity"};
}}