concrete ExpandedLexiconEng of Words = {

  lincat CN = {s : Str};

  lin
    absorbed_CN : CN = {s = "absorbed"}
    accept_CN : CN = {s = "accept"}
    additional_CN : CN = {s = "additional"}
    adequate_CN : CN = {s = "adequate"}
    aim_CN : CN = {s = "aim"}
    aircraft_CN : CN = {s = "aircraft"}
    airplane_CN : CN = {s = "airplane"}
    allow_CN : CN = {s = "allow"}
    alloys_CN : CN = {s = "alloys"}
    already_CN : CN = {s = "already"}
    alter_CN : CN = {s = "alter"}
    aluminium_CN : CN = {s = "aluminium"}
    always_CN : CN = {s = "always"}
    among_CN : CN = {s = "among"}
    amount_CN : CN = {s = "amount"}
    ancient_CN : CN = {s = "ancient"}
    anode_CN : CN = {s = "anode"}
    antennas_CN : CN = {s = "antennas"}
    approximate_CN : CN = {s = "approximate"}
    aqueous_CN : CN = {s = "aqueous"}
    architecture_CN : CN = {s = "architecture"}
    areas_CN : CN = {s = "areas"}
    art_CN : CN = {s = "art"}
    assemblies_CN : CN = {s = "assemblies"}
    assembly_CN : CN = {s = "assembly"}
    asset_CN : CN = {s = "asset"}
    assets_CN : CN = {s = "assets"}
    assumptions_CN : CN = {s = "assumptions"}
    assure_CN : CN = {s = "assure"}
    attention_CN : CN = {s = "attention"}
    audiovisual_CN : CN = {s = "audiovisual"}
    automotive_CN : CN = {s = "automotive"}
    availability_CN : CN = {s = "availability"}
    bank_CN : CN = {s = "bank"}
    banking_CN : CN = {s = "banking"}
    banks_CN : CN = {s = "banks"}
    basically_CN : CN = {s = "basically"}
    become_CN : CN = {s = "become"}
    been_CN : CN = {s = "been"}
    being_CN : CN = {s = "being"}
    benchmarking_CN : CN = {s = "benchmarking"}
    better_CN : CN = {s = "better"}
    bicarbonate_CN : CN = {s = "bicarbonate"}
    board_CN : CN = {s = "board"}
    boost_CN : CN = {s = "boost"}
    boron_CN : CN = {s = "boron"}
    bring_CN : CN = {s = "bring"}
    bulk_CN : CN = {s = "bulk"}
    bus_CN : CN = {s = "bus"}
    business_CN : CN = {s = "business"}
    butane_CN : CN = {s = "butane"}
    cadmium_CN : CN = {s = "cadmium"}
    capacity_CN : CN = {s = "capacity"}
    car_CN : CN = {s = "car"}
    carrying_CN : CN = {s = "carrying"}
    cars_CN : CN = {s = "cars"}
    cash_CN : CN = {s = "cash"}
    cathode_CN : CN = {s = "cathode"}
    cathodes_CN : CN = {s = "cathodes"}
    century_CN : CN = {s = "century"}
    chain_CN : CN = {s = "chain"}
    chains_CN : CN = {s = "chains"}
    challenges_CN : CN = {s = "challenges"}
    chamber_CN : CN = {s = "chamber"}
    change_CN : CN = {s = "change"}
    chiefly_CN : CN = {s = "chiefly"}
    chloride_CN : CN = {s = "chloride"}
    choice_CN : CN = {s = "choice"}
    choices_CN : CN = {s = "choices"}
    choose_CN : CN = {s = "choose"}
    choosing_CN : CN = {s = "choosing"}
    chromium_CN : CN = {s = "chromium"}
    classical_CN : CN = {s = "classical"}
    clearly_CN : CN = {s = "clearly"}
    cobalt_CN : CN = {s = "cobalt"}
    commitment_CN : CN = {s = "commitment"}
    committee_CN : CN = {s = "committee"}
    concentrated_CN : CN = {s = "concentrated"}
    concentrates_CN : CN = {s = "concentrates"}
    concentrating_CN : CN = {s = "concentrating"}
    concept_CN : CN = {s = "concept"}
    concerned_CN : CN = {s = "concerned"}
    conductivity_CN : CN = {s = "conductivity"}
    congress_CN : CN = {s = "congress"}
    conscious_CN : CN = {s = "conscious"}
    consider_CN : CN = {s = "consider"}
    considered_CN : CN = {s = "considered"}
    consistent_CN : CN = {s = "consistent"}
    constitutional_CN : CN = {s = "constitutional"}
    consumer_CN : CN = {s = "consumer"}
    contemporary_CN : CN = {s = "contemporary"}
    continue_CN : CN = {s = "continue"}
    continuing_CN : CN = {s = "continuing"}
    contrary_CN : CN = {s = "contrary"}
    convenience_CN : CN = {s = "convenience"}
    corresponds_CN : CN = {s = "corresponds"}
    cost_CN : CN = {s = "cost"}
    costing_CN : CN = {s = "costing"}
    costs_CN : CN = {s = "costs"}
    council_CN : CN = {s = "council"}
    create_CN : CN = {s = "create"}
    creating_CN : CN = {s = "creating"}
    credit_CN : CN = {s = "credit"}
    critical_CN : CN = {s = "critical"}
    culture_CN : CN = {s = "culture"}
    cuts_CN : CN = {s = "cuts"}
    cyclical_CN : CN = {s = "cyclical"}
    decreases_CN : CN = {s = "decreases"}
    demand_CN : CN = {s = "demand"}
    densities_CN : CN = {s = "densities"}
    density_CN : CN = {s = "density"}
    deputies_CN : CN = {s = "deputies"}
    desire_CN : CN = {s = "desire"}
    developed_CN : CN = {s = "developed"}
    developing_CN : CN = {s = "developing"}
    dichromate_CN : CN = {s = "dichromate"}
    dimensions_CN : CN = {s = "dimensions"}
    distribution_CN : CN = {s = "distribution"}
    does_CN : CN = {s = "does"}
    downside_CN : CN = {s = "downside"}
    driver_CN : CN = {s = "driver"}
    driving_CN : CN = {s = "driving"}
    drop_CN : CN = {s = "drop"}
    drugstore_CN : CN = {s = "drugstore"}
    dx_CN : CN = {s = "dx"}
    ecommerce_CN : CN = {s = "ecommerce"}
    efficiency_CN : CN = {s = "efficiency"}
    efforts_CN : CN = {s = "efforts"}
    elected_CN : CN = {s = "elected"}
    elections_CN : CN = {s = "elections"}
    electricity_CN : CN = {s = "electricity"}
    electrode_CN : CN = {s = "electrode"}
    electrolysis_CN : CN = {s = "electrolysis"}
    electrolyte_CN : CN = {s = "electrolyte"}
    electrolytes_CN : CN = {s = "electrolytes"}
    electronics_CN : CN = {s = "electronics"}
    elsewhere_CN : CN = {s = "elsewhere"}
    emerging_CN : CN = {s = "emerging"}
    emphasis_CN : CN = {s = "emphasis"}
    enable_CN : CN = {s = "enable"}
    energy_CN : CN = {s = "energy"}
    ensure_CN : CN = {s = "ensure"}
    ensuring_CN : CN = {s = "ensuring"}
    equally_CN : CN = {s = "equally"}
    equipment_CN : CN = {s = "equipment"}
    equity_CN : CN = {s = "equity"}
    especially_CN : CN = {s = "especially"}
    establish_CN : CN = {s = "establish"}
    ev_CN : CN = {s = "ev"}
    evolving_CN : CN = {s = "evolving"}
    example_CN : CN = {s = "example"}
    examples_CN : CN = {s = "examples"}
    exceeds_CN : CN = {s = "exceeds"}
    expectation_CN : CN = {s = "expectation"}
    expense_CN : CN = {s = "expense"}
    expenses_CN : CN = {s = "expenses"}
    export_CN : CN = {s = "export"}
    extraordinarily_CN : CN = {s = "extraordinarily"}
    extremely_CN : CN = {s = "extremely"}
    faces_CN : CN = {s = "faces"}
    facilitates_CN : CN = {s = "facilitates"}
    facing_CN : CN = {s = "facing"}
    fact_CN : CN = {s = "fact"}
    factories_CN : CN = {s = "factories"}
    factory_CN : CN = {s = "factory"}
    fairly_CN : CN = {s = "fairly"}
    famous_CN : CN = {s = "famous"}
    far_CN : CN = {s = "far"}
    fibre_CN : CN = {s = "fibre"}
    filament_CN : CN = {s = "filament"}
    financial_CN : CN = {s = "financial"}
    firms_CN : CN = {s = "firms"}
    flawed_CN : CN = {s = "flawed"}
    fluctuating_CN : CN = {s = "fluctuating"}
    fluctuations_CN : CN = {s = "fluctuations"}
    fluoride_CN : CN = {s = "fluoride"}
    focus_CN : CN = {s = "focus"}
    focused_CN : CN = {s = "focused"}
    focusing_CN : CN = {s = "focusing"}
    focussing_CN : CN = {s = "focussing"}
    fuel_CN : CN = {s = "fuel"}
    fuels_CN : CN = {s = "fuels"}
    fund_CN : CN = {s = "fund"}
    fundamentally_CN : CN = {s = "fundamentally"}
    funds_CN : CN = {s = "funds"}
    future_CN : CN = {s = "future"}
    füssen_CN : CN = {s = "füssen"}
    gain_CN : CN = {s = "gain"}
    gas_CN : CN = {s = "gas"}
    gear_CN : CN = {s = "gear"}
    generally_CN : CN = {s = "generally"}
    generate_CN : CN = {s = "generate"}
    generating_CN : CN = {s = "generating"}
    give_CN : CN = {s = "give"}
    given_CN : CN = {s = "given"}
    gives_CN : CN = {s = "gives"}
    giving_CN : CN = {s = "giving"}
    global_CN : CN = {s = "global"}
    good_CN : CN = {s = "good"}
    goods_CN : CN = {s = "goods"}
    grain_CN : CN = {s = "grain"}
    grocery_CN : CN = {s = "grocery"}
    grown_CN : CN = {s = "grown"}
    guarantee_CN : CN = {s = "guarantee"}
    guyed_CN : CN = {s = "guyed"}
    heavily_CN : CN = {s = "heavily"}
    higher_CN : CN = {s = "higher"}
    highly_CN : CN = {s = "highly"}
    historical_CN : CN = {s = "historical"}
    hope_CN : CN = {s = "hope"}
    hoped_CN : CN = {s = "hoped"}
    hydration_CN : CN = {s = "hydration"}
    hydroxide_CN : CN = {s = "hydroxide"}
    ia_CN : CN = {s = "ia"}
    impact_CN : CN = {s = "impact"}
    imperative_CN : CN = {s = "imperative"}
    important_CN : CN = {s = "important"}
    improve_CN : CN = {s = "improve"}
    increase_CN : CN = {s = "increase"}
    increased_CN : CN = {s = "increased"}
    increases_CN : CN = {s = "increases"}
    increasing_CN : CN = {s = "increasing"}
    increasingly_CN : CN = {s = "increasingly"}
    industrial_CN : CN = {s = "industrial"}
    industries_CN : CN = {s = "industries"}
    industry_CN : CN = {s = "industry"}
    inflation_CN : CN = {s = "inflation"}
    inflationary_CN : CN = {s = "inflationary"}
    inherently_CN : CN = {s = "inherently"}
    interest_CN : CN = {s = "interest"}
    invest_CN : CN = {s = "invest"}
    invested_CN : CN = {s = "invested"}
    investing_CN : CN = {s = "investing"}
    investment_CN : CN = {s = "investment"}
    investments_CN : CN = {s = "investments"}
    involving_CN : CN = {s = "involving"}
    irda_CN : CN = {s = "irda"}
    irrelevant_CN : CN = {s = "irrelevant"}
    iud_CN : CN = {s = "iud"}
    jeep_CN : CN = {s = "jeep"}
    key_CN : CN = {s = "key"}
    km_CN : CN = {s = "km"}
    lack_CN : CN = {s = "lack"}
    largely_CN : CN = {s = "largely"}
    larger_CN : CN = {s = "larger"}
    largest_CN : CN = {s = "largest"}
    latest_CN : CN = {s = "latest"}
    legislative_CN : CN = {s = "legislative"}
    legislature_CN : CN = {s = "legislature"}
    less_CN : CN = {s = "less"}
    level_CN : CN = {s = "level"}
    levels_CN : CN = {s = "levels"}
    liquidity_CN : CN = {s = "liquidity"}
    lithium_CN : CN = {s = "lithium"}
    locally_CN : CN = {s = "locally"}
    logistics_CN : CN = {s = "logistics"}
    low_CN : CN = {s = "low"}
    lower_CN : CN = {s = "lower"}
    ls_CN : CN = {s = "ls"}
    machinery_CN : CN = {s = "machinery"}
    magnesium_CN : CN = {s = "magnesium"}
    mainly_CN : CN = {s = "mainly"}
    maintain_CN : CN = {s = "maintain"}
    make_CN : CN = {s = "make"}
    makes_CN : CN = {s = "makes"}
    making_CN : CN = {s = "making"}
    mallock_CN : CN = {s = "mallock"}
    management_CN : CN = {s = "management"}
    manganese_CN : CN = {s = "manganese"}
    manufactured_CN : CN = {s = "manufactured"}
    manufacturers_CN : CN = {s = "manufacturers"}
    manufacturing_CN : CN = {s = "manufacturing"}
    market_CN : CN = {s = "market"}
    means_CN : CN = {s = "means"}
    meant_CN : CN = {s = "meant"}
    measured_CN : CN = {s = "measured"}
    measuring_CN : CN = {s = "measuring"}
    mindset_CN : CN = {s = "mindset"}
    mineral_CN : CN = {s = "mineral"}
    modern_CN : CN = {s = "modern"}
    molybdenum_CN : CN = {s = "molybdenum"}
    morally_CN : CN = {s = "morally"}
    more_CN : CN = {s = "more"}
    most_CN : CN = {s = "most"}
    mostly_CN : CN = {s = "mostly"}
    multilevel_CN : CN = {s = "multilevel"}
    multiple_CN : CN = {s = "multiple"}
    must_CN : CN = {s = "must"}
    mylar_CN : CN = {s = "mylar"}
    natural_CN : CN = {s = "natural"}
    nd_CN : CN = {s = "nd"}
    necessary_CN : CN = {s = "necessary"}
    need_CN : CN = {s = "need"}
    needed_CN : CN = {s = "needed"}
    needs_CN : CN = {s = "needs"}
    neither_CN : CN = {s = "neither"}
    nervousness_CN : CN = {s = "nervousness"}
    nickel_CN : CN = {s = "nickel"}
    nonetheless_CN : CN = {s = "nonetheless"}
    not_CN : CN = {s = "not"}
    noting_CN : CN = {s = "noting"}
    notion_CN : CN = {s = "notion"}
    oil_CN : CN = {s = "oil"}
    operates_CN : CN = {s = "operates"}
    opportunity_CN : CN = {s = "opportunity"}
    optimize_CN : CN = {s = "optimize"}
    optimizing_CN : CN = {s = "optimizing"}
    ores_CN : CN = {s = "ores"}
    originated_CN : CN = {s = "originated"}
    osmotic_CN : CN = {s = "osmotic"}
    outlet_CN : CN = {s = "outlet"}
    outsourcing_CN : CN = {s = "outsourcing"}
    own_CN : CN = {s = "own"}
    oxide_CN : CN = {s = "oxide"}
    oxides_CN : CN = {s = "oxides"}
    packaging_CN : CN = {s = "packaging"}
    paramagnetic_CN : CN = {s = "paramagnetic"}
    parked_CN : CN = {s = "parked"}
    parliament_CN : CN = {s = "parliament"}
    parliamentary_CN : CN = {s = "parliamentary"}
    particular_CN : CN = {s = "particular"}
    particularly_CN : CN = {s = "particularly"}
    partly_CN : CN = {s = "partly"}
    passenger_CN : CN = {s = "passenger"}
    pay_CN : CN = {s = "pay"}
    paying_CN : CN = {s = "paying"}
    percent_CN : CN = {s = "percent"}
    permanganate_CN : CN = {s = "permanganate"}
    pessimism_CN : CN = {s = "pessimism"}
    petroleum_CN : CN = {s = "petroleum"}
    phosphate_CN : CN = {s = "phosphate"}
    pickup_CN : CN = {s = "pickup"}
    pledge_CN : CN = {s = "pledge"}
    political_CN : CN = {s = "political"}
    poorly_CN : CN = {s = "poorly"}
    portfolio_CN : CN = {s = "portfolio"}
    possible_CN : CN = {s = "possible"}
    potassium_CN : CN = {s = "potassium"}
    potential_CN : CN = {s = "potential"}
    power_CN : CN = {s = "power"}
    precipitates_CN : CN = {s = "precipitates"}
    premise_CN : CN = {s = "premise"}
    pressures_CN : CN = {s = "pressures"}
    previously_CN : CN = {s = "previously"}
    price_CN : CN = {s = "price"}
    prices_CN : CN = {s = "prices"}
    primarily_CN : CN = {s = "primarily"}
    principally_CN : CN = {s = "principally"}
    priority_CN : CN = {s = "priority"}
    probability_CN : CN = {s = "probability"}
    problematic_CN : CN = {s = "problematic"}
    producing_CN : CN = {s = "producing"}
    product_CN : CN = {s = "product"}
    production_CN : CN = {s = "production"}
    products_CN : CN = {s = "products"}
    profile_CN : CN = {s = "profile"}
    profoundly_CN : CN = {s = "profoundly"}
    progress_CN : CN = {s = "progress"}
    promise_CN : CN = {s = "promise"}
    promised_CN : CN = {s = "promised"}
    promises_CN : CN = {s = "promises"}
    promising_CN : CN = {s = "promising"}
    proportion_CN : CN = {s = "proportion"}
    proved_CN : CN = {s = "proved"}
    provide_CN : CN = {s = "provide"}
    radically_CN : CN = {s = "radically"}
    radius_CN : CN = {s = "radius"}
    raise_CN : CN = {s = "raise"}
    rapidly_CN : CN = {s = "rapidly"}
    rate_CN : CN = {s = "rate"}
    rates_CN : CN = {s = "rates"}
    rather_CN : CN = {s = "rather"}
    ratio_CN : CN = {s = "ratio"}
    recent_CN : CN = {s = "recent"}
    recently_CN : CN = {s = "recently"}
    reduce_CN : CN = {s = "reduce"}
    reduced_CN : CN = {s = "reduced"}
    regarded_CN : CN = {s = "regarded"}
    regions_CN : CN = {s = "regions"}
    relatively_CN : CN = {s = "relatively"}
    remained_CN : CN = {s = "remained"}
    remarkably_CN : CN = {s = "remarkably"}
    renewable_CN : CN = {s = "renewable"}
    representatives_CN : CN = {s = "representatives"}
    requires_CN : CN = {s = "requires"}
    resources_CN : CN = {s = "resources"}
    response_CN : CN = {s = "response"}
    restaurants_CN : CN = {s = "restaurants"}
    retail_CN : CN = {s = "retail"}
    retailer_CN : CN = {s = "retailer"}
    retailers_CN : CN = {s = "retailers"}
    revenue_CN : CN = {s = "revenue"}
    rise_CN : CN = {s = "rise"}
    risen_CN : CN = {s = "risen"}
    rising_CN : CN = {s = "rising"}
    ruling_CN : CN = {s = "ruling"}
    rx_CN : CN = {s = "rx"}
    sales_CN : CN = {s = "sales"}
    salts_CN : CN = {s = "salts"}
    sector_CN : CN = {s = "sector"}
    sectors_CN : CN = {s = "sectors"}
    secure_CN : CN = {s = "secure"}
    seek_CN : CN = {s = "seek"}
    seen_CN : CN = {s = "seen"}
    senate_CN : CN = {s = "senate"}
    serious_CN : CN = {s = "serious"}
    serous_CN : CN = {s = "serous"}
    shop_CN : CN = {s = "shop"}
    shops_CN : CN = {s = "shops"}
    shortage_CN : CN = {s = "shortage"}
    should_CN : CN = {s = "should"}
    shows_CN : CN = {s = "shows"}
    significant_CN : CN = {s = "significant"}
    significantly_CN : CN = {s = "significantly"}
    similar_CN : CN = {s = "similar"}
    similarly_CN : CN = {s = "similarly"}
    slowdown_CN : CN = {s = "slowdown"}
    small_CN : CN = {s = "small"}
    sme_CN : CN = {s = "sme"}
    sourcing_CN : CN = {s = "sourcing"}
    specialty_CN : CN = {s = "specialty"}
    speeding_CN : CN = {s = "speeding"}
    spending_CN : CN = {s = "spending"}
    step_CN : CN = {s = "step"}
    storage_CN : CN = {s = "storage"}
    store_CN : CN = {s = "store"}
    stores_CN : CN = {s = "stores"}
    strategy_CN : CN = {s = "strategy"}
    strong_CN : CN = {s = "strong"}
    style_CN : CN = {s = "style"}
    sulfide_CN : CN = {s = "sulfide"}
    sulfur_CN : CN = {s = "sulfur"}
    superconducting_CN : CN = {s = "superconducting"}
    supermarket_CN : CN = {s = "supermarket"}
    supermarkets_CN : CN = {s = "supermarkets"}
    supplies_CN : CN = {s = "supplies"}
    supply_CN : CN = {s = "supply"}
    supposed_CN : CN = {s = "supposed"}
    supreme_CN : CN = {s = "supreme"}
    surfactant_CN : CN = {s = "surfactant"}
    swings_CN : CN = {s = "swings"}
    sx_CN : CN = {s = "sx"}
    taurus_CN : CN = {s = "taurus"}
    tax_CN : CN = {s = "tax"}
    taxi_CN : CN = {s = "taxi"}
    tec_CN : CN = {s = "tec"}
    technically_CN : CN = {s = "technically"}
    technology_CN : CN = {s = "technology"}
    textile_CN : CN = {s = "textile"}
    than_CN : CN = {s = "than"}
    titanium_CN : CN = {s = "titanium"}
    totally_CN : CN = {s = "totally"}
    tractor_CN : CN = {s = "tractor"}
    tradition_CN : CN = {s = "tradition"}
    traditional_CN : CN = {s = "traditional"}
    trailer_CN : CN = {s = "trailer"}
    transferrin_CN : CN = {s = "transferrin"}
    trend_CN : CN = {s = "trend"}
    truck_CN : CN = {s = "truck"}
    trucks_CN : CN = {s = "trucks"}
    tubes_CN : CN = {s = "tubes"}
    tubing_CN : CN = {s = "tubing"}
    turbulence_CN : CN = {s = "turbulence"}
    unanimously_CN : CN = {s = "unanimously"}
    uncertainties_CN : CN = {s = "uncertainties"}
    uncertainty_CN : CN = {s = "uncertainty"}
    uniaxial_CN : CN = {s = "uniaxial"}
    unique_CN : CN = {s = "unique"}
    unlike_CN : CN = {s = "unlike"}
    unusual_CN : CN = {s = "unusual"}
    useful_CN : CN = {s = "useful"}
    valuations_CN : CN = {s = "valuations"}
    vanadium_CN : CN = {s = "vanadium"}
    variance_CN : CN = {s = "variance"}
    varies_CN : CN = {s = "varies"}
    vehicle_CN : CN = {s = "vehicle"}
    vehicles_CN : CN = {s = "vehicles"}
    very_CN : CN = {s = "very"}
    volatility_CN : CN = {s = "volatility"}
    volt_CN : CN = {s = "volt"}
    voted_CN : CN = {s = "voted"}
    warehousing_CN : CN = {s = "warehousing"}
    ways_CN : CN = {s = "ways"}
    weakness_CN : CN = {s = "weakness"}
    were_CN : CN = {s = "were"}
    whose_CN : CN = {s = "whose"}
    widely_CN : CN = {s = "widely"}
    width_CN : CN = {s = "width"}
    willing_CN : CN = {s = "willing"}
    willingness_CN : CN = {s = "willingness"}
    wish_CN : CN = {s = "wish"}
    works_CN : CN = {s = "works"}
    worth_CN : CN = {s = "worth"}
    xa_CN : CN = {s = "xa"}
    yet_CN : CN = {s = "yet"}
    zero_CN : CN = {s = "zero"}
    zinc_CN : CN = {s = "zinc"}
    zt_CN : CN = {s = "zt"}

}}