# Generated by Django 6.0.3 on 2026-03-29 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LexicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200)),
                ('gf_function', models.CharField(blank=True, db_index=True, max_length=200)),
                ('gf_cat', models.CharField(blank=True, max_length=20)),
                ('in_wordnet', models.BooleanField(default=False)),
                ('translations', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('word', 'gf_function')},
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source_lang', models.CharField(max_length=10)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('imdb_id', 'source_lang')},
            },
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to=settings.AUTH_USER_MODEL)),
                ('source_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lessons.sourcedocument')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('word_translation_mc', 'Word translation (MC)'), ('sentence_translation', 'Sentence translation (open)'), ('sentence_mc', 'Sentence translation (MC)'), ('fill_blank', 'Fill in the blank'), ('conjugation_table', 'Conjugation table')], max_length=40)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('pattern', models.JSONField(default=dict)),
                ('gf_function', models.CharField(blank=True, max_length=200)),
                ('gf_cat', models.CharField(blank=True, max_length=20)),
                ('prompt', models.TextField()),
                ('prompt_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('correct_answer', models.TextField()),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='lessons.lessonsession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'target_lang', 'created_at'], name='lessons_exe_user_id_73da29_idx'), models.Index(fields=['gf_function'], name='lessons_exe_gf_func_f334cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='LexicalAlternate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gf_function', models.CharField(max_length=200)),
                ('translations', models.JSONField(default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternates', to='lessons.lexicalentry')),
            ],
            options={
                'unique_together': {('entry', 'gf_function')},
            },
        ),
        migrations.CreateModel(
            name='LessonWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('alternate_counts', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_words', to='lessons.lessonsession')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_words', to='lessons.lexicalentry')),
            ],
            options={
                'unique_together': {('session', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('tree', models.TextField()),
                ('pattern', models.JSONField(default=dict)),
                ('linearizations', models.JSONField(default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.lexicalentry')),
            ],
            options={
                'unique_together': {('entry', 'tree')},
            },
        ),
        migrations.CreateModel(
            name='UserLanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('skill_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_lang', 'target_lang')},
            },
        ),
    ]
