# Generated by Django 6.0.3 on 2026-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('words_ready', 'Words ready'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
